Add MAIN_PROJECT check for test and install options
nlohmann/json pull request #2514
Opened 2020-12-09 10:56 UTC by globberwops

[Describe your pull request here. Please read the text below the line, and make sure you follow the checklist.]

This resolves #2513 by checking if this is the main project in a CMake project tree.
`JSON_BuildTests` and `JSON_Install` will only be set to `ON` if this is the main project.
CTest will only be included, if `JSON_BuildTests` is set to `ON`.
`BUILD_TESTING` will therefore only be set, if this is the main project.

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

2020-12-10 06:50 UTC, ayushsinghsrinet commented
Can you teach me c++

2020-12-12 15:08 UTC, YarikTH commented
For reference, here is the same purpose code from [{fmt}](https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt)
```cmake
# Determine if fmt is built as a subproject (using add_subdirectory)
# or if it is the master project.
set(MASTER_PROJECT OFF)
if (CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
  set(MASTER_PROJECT ON)
  message(STATUS "CMake version: ${CMAKE_VERSION}")
endif ()
...
...
...
# Options that control generation of various targets.
option(FMT_DOC "Generate the doc target." ${MASTER_PROJECT})
option(FMT_INSTALL "Generate the install target." ${MASTER_PROJECT})
option(FMT_TEST "Generate the test target." ${MASTER_PROJECT})
option(FMT_FUZZ "Generate the fuzz target." OFF)
option(FMT_CUDA_TEST "Generate the cuda-test target." OFF)
option(FMT_OS "Include core requiring OS (Windows/Posix) " ON)
```

So it might be a good idea at least copy explanatory comment and maybe use `CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR` check instead of `CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR`.

2020-12-12 16:06 UTC, nlohmann requested changes

2020-12-12 16:06 UTC, nlohmann commented on CMakeLists.txt
> +## MAIN_PROJECT CHECK
Please add documentation similar to https://github.com/nlohmann/json/pull/2514#issuecomment-743769382.

2020-12-14 09:48 UTC, nlohmann commented on CMakeLists.txt
> +    include(CTest) #adds option BUILD_TESTING (default ON)
```suggestion
    include(CTest)
```

This comment is not needed any more.

2020-12-14 09:50 UTC, nlohmann requested changes
A last change request, otherwise looks good to me.

2020-12-14 12:41 UTC, nlohmann approved these changes
Looks good to me.

2020-12-14 12:41 UTC, merged

2020-12-14 12:41 UTC, nlohmann commented
Thanks!

2020-12-14 17:26 UTC, globberwops commented
@nlohmann Thank you 👍🏻