readme: harmonize versions; fix `~` char display
nlohmann/json pull request #2582
Opened 2021-01-11 18:39 UTC by bl-ue

- Harmonizes references to the project version (3.9.1)
- Fixes display of `~` character in GitHub in compiler table

2021-01-12 18:44 UTC, YarikTH commented
I'm not a maintainer, but here is my IMO. This PR should be divided into "readme: harmonize versions" and "readme: fix `~` char display".

While ~ display fix is a really useful fix, version harmonization is discussible.

Nobody wants to maintain this manual version harmonization, so version numbers in readme will be outdated immediately after another release. I think, that all such mentions should be universal one like ```merely add `nlohmann_json/x.y.z` to your `conanfile`'s requires, where `x.y.z` is the release version you want to use.``` or makefile should contain some new step for updating version in the readme.md (using md commentary as a mark?). Otherwise, I fear it's useless work.

2021-01-12 18:47 UTC, bl-ue commented
Okay @YarikTH.  I though that @nlohmann could update versions in the README just the same way he does in the rest of the project although I haven't actually checked to if it's automated or not (just a global find/replace?)

2021-01-12 18:51 UTC, YarikTH commented
> I thought that @nlohmann could update versions in the README just the same way he does in the rest of the project although I haven't actually checked to if it's automated or not (just a global find/replace?)

I have no idea, but the fact, that version numbers in readme are outdated, means that there is either no such automatization step, or it is not executed for a very long time. So maybe it's time to invent one and integrate into the release process.

2021-01-12 18:52 UTC, bl-ue commented
Good idea.  I'll do some research and report back.

2021-01-12 18:56 UTC, bl-ue commented
@nlohmann is the version updated as in commit https://github.com/nlohmann/json/commit/b3e5cb7f20dcc5c806e418df34324eca60d17d4e through automation of any sort?

2021-01-12 18:59 UTC, YarikTH commented
> just a global find/replace?

It's a terrible idea.

Because at least readme contains a lot of version numbers of another software. For e.g. clang

```
Clang 3.5.0 (3.5.0-4ubuntu2~trusty2) | Ubuntu 14.04.5 LTS | Travis
Clang 3.6.2 (3.6.2-svn240577-1~exp1) | Ubuntu 14.04.5 LTS | Travis
Clang 3.7.1 (3.7.1-svn253571-1~exp1) | Ubuntu 14.04.5 LTS | Travis
Clang 3.8.0 (3.8.0-2ubuntu3~trusty5) | Ubuntu 14.04.5 LTS | Travis
Clang 3.9.1 (3.9.1-4ubuntu3~14.04.3) | Ubuntu 14.04.5 LTS | Travis
Clang 4.0.1 (4.0.1-svn305264-1~exp1) | Ubuntu 14.04.5 LTS | Travis
```

There is even a full match with the current release version. So all the versions of all the mentioned software would become "the same release as nlohmann/json. Like a rolling snowball.

2021-01-12 19:03 UTC, bl-ue commented
That wouldn't be good, but then, how does he do it currently? 🤔

2021-01-14 20:32 UTC, nlohmann commented
Version numbers are updated in a script I run when I prepare a release. The version numbers of the README file are usually not part of it. The versions for the package managers are just examples - I am not a maintainer for those and I'm not willing to check regularly which version is available where.

So I concur with https://github.com/nlohmann/json/pull/2582#issuecomment-758860381 and would like to see a PR handling the tildes, but rather not touch the version numbers in the README file.

2021-01-14 20:39 UTC, nlohmann requested changes
Please do not adjust the version numbers, see https://github.com/nlohmann/json/pull/2582#issuecomment-760458842.

2021-01-14 21:11 UTC, nlohmann approved these changes
Looks good to me.

2021-01-14 21:11 UTC, merged

2021-01-14 21:11 UTC, nlohmann commented
Thanks!