Fixes #2730
nlohmann/json pull request #2731
Opened 2021-04-21 09:07 UTC by theShmoo

Added define JSON_VERSION_IS_PREDEFINED
for skipping automatic JSON_HAS_CPP_* detection

2021-04-21 09:49 UTC, nlohmann requested changes
Please run `make amalgamate` to make sure the single header is properly generated. The CI currently fails because this.

2021-04-24 10:34 UTC, nlohmann requested changes

2021-04-24 10:34 UTC, nlohmann commented on include/nlohmann/detail/macro_scope.hpp
> +#ifndef JSON_VERSION_IS_PREDEFINED
How about replacing this with

```cpp
#if !defined(JSON_HAS_CPP_20) && !defined(JSON_HAS_CPP_17) && !defined(JSON_HAS_CPP_14)
```

Wouldn't this have the same effect, but does not need an additional macro?

2021-04-24 12:04 UTC, theShmoo commented
Yeah this sounds great!

But I would have to define the new define JSON_HAS_CPP_11

Is this ok?

Niels Lohmann ***@***.***> schrieb am Sa., 24. Apr. 2021,
12:34:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In include/nlohmann/detail/macro_scope.hpp
> <https://github.com/nlohmann/json/pull/2731#discussion_r619641608>:
>
> > @@ -20,15 +20,18 @@
>  #endif
>
>  // C++ language standard detection
> -#if (defined(__cplusplus) && __cplusplus >= 202002L) || (defined(_MSVC_LANG) && _MSVC_LANG >= 202002L)
> -    #define JSON_HAS_CPP_20
> -    #define JSON_HAS_CPP_17
> -    #define JSON_HAS_CPP_14
> -#elif (defined(__cplusplus) && __cplusplus >= 201703L) || (defined(_HAS_CXX17) && _HAS_CXX17 == 1) // fix for issue #464
> -    #define JSON_HAS_CPP_17
> -    #define JSON_HAS_CPP_14
> -#elif (defined(__cplusplus) && __cplusplus >= 201402L) || (defined(_HAS_CXX14) && _HAS_CXX14 == 1)
> -    #define JSON_HAS_CPP_14
> +// if the user wants to manually specify the used c++ version this is skipped
> +#ifndef JSON_VERSION_IS_PREDEFINED
>
> How about replacing this with
>
> #if !defined(JSON_HAS_CPP_20) && !defined(JSON_HAS_CPP_17) && !defined(JSON_HAS_CPP_14)
>
> Wouldn't this have the same effect, but does not need an additional macro?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nlohmann/json/pull/2731#pullrequestreview-644020859>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABK7ANYJILJLC7MGERGB6ZDTKKNE3ANCNFSM43J5X4BQ>
> .
>

2021-04-24 12:09 UTC, nlohmann commented
> Yeah this sounds great! But I would have to define the new define JSON_HAS_CPP_11 Is this ok?

Oh right - I forgot this. Then I guess the best would be the following:

- Adjust the `if` to also check for `JSON_HAS_CPP11`.
- Define `JSON_HAS_CPP11` if now other C++ standard has been detected. This way, the (otherwise unused) variable is at least always set. This allows to maybe make some compile-time decisions later on, but also to "force" any C++ standard different to how it would have been detected.

What do you think?

2021-04-24 12:18 UTC, theShmoo commented
Sounds great! Will do tomorrow!

Niels Lohmann ***@***.***> schrieb am Sa., 24. Apr. 2021,
14:09:

> Yeah this sounds great! But I would have to define the new define
> JSON_HAS_CPP_11 Is this ok?
>
> Oh right - I forgot this. Then I guess the best would be the following:
>
>    - Adjust the if to also check for JSON_HAS_CPP11.
>    - Define JSON_HAS_CPP11 if now other C++ standard has been detected.
>    This way, the (otherwise unused) variable is at least always set. This
>    allows to maybe make some compile-time decisions later on, but also to
>    "force" any C++ standard different to how it would have been detected.
>
> What do you think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nlohmann/json/pull/2731#issuecomment-826083472>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABK7AN2R46W4BH2BT7Y6GDDTKKYHXANCNFSM43J5X4BQ>
> .
>

2021-04-29 07:54 UTC, nlohmann approved these changes
Looks good to me.

2021-04-29 07:55 UTC, merged

2021-04-29 07:55 UTC, nlohmann commented
Thanks!

2021-04-30 07:55 UTC, theShmoo commented
Thank you very much for your support!