All: fix warnings when compiling with -Wswitch-enum
nlohmann/json pull request #2927
Opened 2021-08-12 14:57 UTC by fhuberts

Signed-off-by: Ferry Huberts <ferry.huberts@pelagic.nl>

[Describe your pull request here. Please read the text below the line, and make sure you follow the checklist.]

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

2021-08-12 17:44 UTC, nlohmann requested changes
I am surprised that fixing this warning does not come at the expense of another warning coming up - at least in the past, we always have had to suppress one of the switch warnings.

Can you please remove the `-Wno-switch-enum` from https://github.com/nlohmann/json/blob/develop/cmake/ci.cmake#L102 and replace `-Wno-switch-enum` by `-Wswitch-enum` in https://github.com/nlohmann/json/blob/develop/cmake/ci.cmake#L329? Then the CI is actually checking whether the warning is really gone.

2021-08-12 18:04 UTC, fhuberts commented
> I am surprised that fixing this warning does not come at the expense of another warning coming up - at least in the past, we always have had to suppress one of the switch warnings.
> 
> Can you please remove the `-Wno-switch-enum` from https://github.com/nlohmann/json/blob/develop/cmake/ci.cmake#L102 and replace `-Wno-switch-enum` by `-Wswitch-enum` in https://github.com/nlohmann/json/blob/develop/cmake/ci.cmake#L329? Then the CI is actually checking whether the warning is really gone.

Done.
Works fine for me on Fedora 34.
```$ g++ --version
g++ (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

2021-08-12 21:30 UTC, gregmarr commented
@nlohmann The warning that you're thinking of is `-Wcovered-switch-default` which is part of `-Weverything` on Clang.  This will warn because these switches have all the cases covered AND have a `default:` statement.

https://github.com/nlohmann/json/pull/555#issuecomment-294304901

2021-08-13 06:36 UTC, fhuberts commented
Works fine on Debian 10.10 with gcc as well.
So it indeed seems that conflicting options are to blame here.

2021-08-13 06:40 UTC, fhuberts commented
I checked the other issues that are mentioned (did no see them before).

If the currently feeling is the same as before, then no problem because I'll just keep this as a private patch in our repo.

Personally I do prefer the gcc way because it makes the code explicit and therefore easier to read and reason about.
My 2 cents.

2021-08-13 10:37 UTC, nlohmann requested changes
I think the warnings raised by Clang and GCC all complain about some switches which have not yet been touched by the PR. I think they can be fixed similarly.

2021-08-13 10:45 UTC, fhuberts commented
I'm a bit surprised that there are now errors on files I didn't touch.
Like ```/home/runner/work/json/json/include/nlohmann/detail/input/binary_reader.hpp```.
I compiled as prescribed.

2021-08-13 10:46 UTC, nlohmann commented
> I'm a bit surprised that there are now errors on files I didn't touch.
> Like `/home/runner/work/json/json/include/nlohmann/detail/input/binary_reader.hpp`.
> I compiled as prescribed.

Did you compile the unit test suite?

2021-08-13 10:47 UTC, fhuberts commented
> > I'm a bit surprised that there are now errors on files I didn't touch.
> > Like `/home/runner/work/json/json/include/nlohmann/detail/input/binary_reader.hpp`.
> > I compiled as prescribed.
> 
> Did you compile the unit test suite?

I followed the instructions of the PR, I did as described here: https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests

2021-08-13 10:48 UTC, nlohmann commented
I see - but I guess the CI uses a different set of warnings.

2021-08-13 10:49 UTC, fhuberts commented
Then if you let me know how I should compile it, I'll see if I can fix those warnings as well.

2021-08-13 10:52 UTC, nlohmann commented
Try this:

```sh
mkdir build
cd build
cmake .. -DJSON_CI=ON
```

Then

```sh
make ci_test_gcc
```

for GCC with all flags and

```sh
make ci_test_clang
```

for Clang with all flags.

2021-08-13 10:55 UTC, nlohmann commented
(Or just check out the results of https://github.com/nlohmann/json/pull/2927/checks?check_run_id=3314908857 and https://github.com/nlohmann/json/pull/2927/checks?check_run_id=3314909773)

2021-08-13 12:01 UTC, fhuberts commented
Adjusted.
```make ci_test_gcc``` didn't work for me, the clang build did work
Might be because I have ccache installed

2021-08-13 13:17 UTC, nlohmann approved these changes
Looks good to me.

2021-08-13 13:27 UTC, nlohmann requested changes
Please also add `// LCOV_EXCL_LINE` to the added branches, as the coverage has decreased.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/159488/129364089-285deba0-bb47-4d97-8eb6-78461208046c.png">

See https://coveralls.io/builds/42131077.

2021-08-13 15:37 UTC, nlohmann approved these changes
Looks good to me.

2021-08-13 15:38 UTC, nlohmann commented
Thanks for the patience! I will merge this as soon as the CI is done.

2021-08-13 17:32 UTC, merged

2021-08-13 17:37 UTC, fhuberts commented
success!
tnx!