Updating the Homebrew Command
nlohmann/json pull request #2943
Opened 2021-08-18 09:59 UTC by amirmasoudabdol

So, apparently, `homebrew/core` has a `nlohmann-json` formula. This means that, even after tapping to `nlohmann/json`, the user has to specify what formula should be used. and running `brew install nlohmann-json` will use the `homebrew/core` instead of the formula located at `nlohmann/json`. To resolve this, the install command needs to be more explicit and point to your formula.

You can point to your formula in two fashions, `brew install nlohmann_json` or more explicitly, `brew install nlohmann/json/nlohmann_json`. This distinguish it from the existing formula `homebrew/core/nlohmann-json` which I believe is not being maintained by people in this repo.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

2021-08-18 11:24 UTC, amirmasoudabdol commented
I think this needs more attention. I just realised from some test that installing `nlohmann_json` from your `nlohmann/json` does not setup the CMake correctly. This might be because I had the version from `homebrew/core` installed and now it's being confused. But, I've tried a clean install and had the same problem. 

As we discussed on Twitter, if you are willing to drop the `nlohmann/json` Formula, then we can make on the `homebrew/core` Formula and keep that updated. I try to update the homebrew formula for this update and reflect it on the README. However, we need to have this as part of the release checklist to make sure that it's been keeping up to date.

2021-08-18 15:00 UTC, amirmasoudabdol commented
The [PR at homebrew/core](https://github.com/Homebrew/homebrew-core/pull/83479) has been approved, and will be merged soon. So, I think this one can go after that one.

2021-08-18 17:51 UTC, nlohmann requested changes
Can you please also adjust the documentation in https://github.com/nlohmann/json/blob/develop/doc/mkdocs/docs/integration/package_managers.md#homebrew ? Thanks!

2021-08-19 08:00 UTC, amirmasoudabdol commented
I think that should be done!

2021-08-19 08:45 UTC, nlohmann approved these changes
Looks good to me.

2021-08-19 10:03 UTC, merged

2021-08-19 10:04 UTC, nlohmann commented
Thanks!