.github/workflows/windows.yml: Add support for Visual Studio 2022
nlohmann/json pull request #3295
Opened 2022-01-25 14:08 UTC by t-b

This is available in github actions since some time now [1].

[1]: https://github.com/actions/virtual-environments/issues/3949

2022-01-25 18:48 UTC, nlohmann requested changes
Can you please also edit the "Supported Compilers" section in the README (https://github.com/nlohmann/json/blob/develop/README.md?plain=1#L1036)?

2022-01-25 19:31 UTC, t-b commented
Done.

2022-01-25 19:32 UTC, nlohmann commented
> Done.

Thanks, can you also add a line to the table?

2022-01-25 19:51 UTC, t-b commented
Jeep.

2022-01-26 08:56 UTC, nlohmann approved these changes
Looks good to me.

2022-01-26 08:57 UTC, merged

2022-01-26 08:57 UTC, nlohmann commented
Thanks a lot!