Avoid clash with Arduino defines
nlohmann/json pull request #3338
Opened 2022-02-17 19:06 UTC by DarkZeros

* Arduino defines B0/B1 in "binary.h"
     #define B0 0
     #define B1 1
  This clashes with names of the template
  variables in conjuction

* Renaming them to "B" rather than "B1"
  Now it can be used as-is in Arduino projects

2022-02-18 17:34 UTC, gregmarr commented
Wow, how incredibly short-sighted of that project, polluting the global namespace like that.

2022-02-18 17:37 UTC, nlohmann requested changes

2022-02-18 17:37 UTC, nlohmann commented on include/nlohmann/detail/meta/type_traits.hpp
> +template<class B> struct conjunction<Bx> : B { };
The `Bx` should be ´B`.

2022-04-03 15:16 UTC, nlohmann commented on include/nlohmann/detail/meta/type_traits.hpp
> +template<class B> struct conjunction<Bx> : B { };
```suggestion
template<class B> struct conjunction<B> : B { };
```

2022-04-03 15:18 UTC, nlohmann commented on single_include/nlohmann/json.hpp
> +template<class B> struct conjunction<Bx> : B { };
```suggestion
template<class B> struct conjunction<B> : B { };
```

2022-04-03 16:33 UTC, nlohmann approved these changes
Looks good to me.

2022-04-03 16:33 UTC, merged