Refactor unit tests to use more convenient doctest assertion macros
nlohmann/json pull request #3393
Opened 2022-03-17 15:28 UTC by kkarbowiak

This PR refactors unit tests to use more convenient doctest assertion macros, as discussed in issue #3365.

The bulk of the change was done automatically, using a regexp replace, with some manual adjustments.

In the process, I found several unit tests that rely on the side effects of running two assertion macros and got broken by running a single one. Those tests are left untouched, to keep them passing. I think I will try to address those is a separate PR.

2022-03-19 12:42 UTC, nlohmann approved these changes
Looks good to me.

2022-03-19 14:02 UTC, nlohmann commented
There are still tests failing in the CI. Can you please update from the latest `develop` branch?

2022-03-19 14:02 UTC, nlohmann requested changes
There are still tests failing in the CI. Can you please update from the latest `develop` branch?

2022-03-20 09:31 UTC, kkarbowiak commented
> There are still tests failing in the CI. Can you please update from the latest `develop` branch?

As far as I can tell, my fork is up to date with regards to the `develop` branch.

Also, it seems that the only CI builds that did not succeed are the MSVC2017 ones. Those got canceled, presumably due to Github deprecating the Windows 2016 environment. Please have a look at the bottom of [this page](https://github.com/nlohmann/json/actions/runs/1999234302). If I'm mistaken though, I'll be happy to do any corrections necessary to make the CI builds pass.

2022-03-24 08:23 UTC, nlohmann commented
The latest develop branch runs all CI tests.

2022-03-24 14:54 UTC, nlohmann approved these changes
Looks good to me.

2022-03-24 14:55 UTC, merged

2022-03-24 14:55 UTC, nlohmann commented
Thanks a lot!

2022-04-04 07:10 UTC, kkarbowiak commented
Thank you, too.