CI: windows-2016 has been deprecated; remove jobs
nlohmann/json pull request #3416
Opened 2022-04-04 04:50 UTC by falbrechtskirchinger

As previously mentioned windows-2016 is now deprecated. Remove msvc2017* jobs from the workflow.
GH offers no replacement for jobs requiring "Visual Studio 15 2017".

2022-04-04 05:15 UTC, nlohmann requested changes
Can you please also update the README section and remove the lines for MSVC 2017?

2022-04-04 07:11 UTC, falbrechtskirchinger commented
Done.

The compiler list in README needs a thorough update at some point. GCC 11 (experimental) doesn't seem right, for example.

2022-04-04 11:18 UTC, merged

2022-04-04 11:18 UTC, nlohmann commented
Thanks!

2022-04-06 11:55 UTC, nlohmann commented
> Done.
> 
> The compiler list in README needs a thorough update at some point. GCC 11 (experimental) doesn't seem right, for example.

Fixed in #3420.