Add error message if test suite cannot be found
nlohmann/json pull request #3585
Opened 2022-07-17 12:26 UTC by nlohmann

Fixes #3584

2022-07-17 12:33 UTC, falbrechtskirchinger requested changes

2022-07-17 12:33 UTC, falbrechtskirchinger commented on tests/src/unit-testsuites.cpp
> +#include "make_test_data_available.hpp"
Remove. Duplicated below.

2022-07-17 13:13 UTC, nlohmann commented on tests/src/unit-testsuites.cpp
> +#include "make_test_data_available.hpp"
Done.

2022-07-18 22:06 UTC, gregmarr commented on tests/src/make_test_data_available.hpp
> +    return file.operator bool();
Suggest `file != nullptr`

2022-07-20 10:41 UTC, merged