Add documentation for comparing json and ordered_json
nlohmann/json pull request #3599
Opened 2022-07-23 13:06 UTC by nlohmann

Closes  #3443

2022-07-23 14:47 UTC, falbrechtskirchinger commented on docs/mkdocs/docs/api/basic_json/operator_eq.md
> +    depends on whether [`nlohmann::json`](../json.md) order [`nlohmann::ordered_json`](../ordered_json.md) is used:
"or" oder "order"? :-)

```suggestion
    depends on whether [`nlohmann::json`](../json.md) or [`nlohmann::ordered_json`](../ordered_json.md) is used:
```

2022-07-23 14:53 UTC, falbrechtskirchinger requested changes

2022-07-23 14:53 UTC, falbrechtskirchinger commented on docs/mkdocs/docs/api/basic_json/operator_eq.md
> +    objects
```suggestion
    Comparing different `basic_json` specializations can have surprising effects. For instance, the result of comparing
    the JSON objects
```

2022-07-23 14:53 UTC, falbrechtskirchinger commented on docs/mkdocs/docs/api/basic_json/operator_eq.md
> +    depends on whether [`nlohmann::json`](../json.md) order [`nlohmann::ordered_json`](../ordered_json.md) is used:
"or" oder "order"? :-)

```suggestion
    depends on whether [`nlohmann::json`](../json.md) or [`nlohmann::ordered_json`](../ordered_json.md) is used:
```

2022-07-23 18:54 UTC, merged

2022-07-24 01:34 UTC, akontsevich commented
I would extend the doc. Still not clear how to compare different JSON types. I converted one to another first.