Add Discord badge to README
nlohmann/json pull request #3651
Opened 2022-08-02 08:34 UTC by falbrechtskirchinger

Add the Shields.io Discord badge with a permanent invite link to the README.

> To use the Discord badge a Discord server admin must enable the widget setting on the server.

2022-08-02 15:09 UTC, nlohmann commented
I think we should make clear that Discord will not be a support channel, but a means to coordinate the development. A badge is fine, but this should also go to the README.

2022-08-02 20:20 UTC, nlohmann commented
FYI: Enabled the widget in the server settings.

2022-08-02 20:25 UTC, nlohmann requested changes
We should mention in https://github.com/nlohmann/json#support that the Discord channel is to coordinate library development and not meant as a means to provide support.

2022-08-03 04:01 UTC, falbrechtskirchinger commented
If the server starts attracting a healthy number of people, I don't see why we couldn't add a dedicated support channel?

2022-08-03 07:08 UTC, nlohmann commented
> If the server starts attracting a healthy number of people, I don't see why we couldn't add a dedicated support channel?

I am hesitant, because I still get a lot of emails from people asking support, and I stopped answering (and only referred them to GitHub), because such a 1:1 communication has no benefit to others.

Let's just see what happens now, and we can still change our policy later.

2022-08-03 07:08 UTC, nlohmann approved these changes
Looks good to me.

2022-08-03 07:17 UTC, merged