Amalgamate the forward declaration header
nlohmann/json pull request #3679
Opened 2022-08-05 18:37 UTC by falbrechtskirchinger

As discussed, we need to amalgamate `json_fwd.hpp` to make it usable as a standalone file (again).

2022-08-05 21:18 UTC, nlohmann requested changes
Please also adjust:

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md

2022-08-06 10:16 UTC, shaischaudhry approved these changes

2022-08-07 04:33 UTC, falbrechtskirchinger commented
I've updated `integration/index.md` as well.

2022-08-07 04:39 UTC, falbrechtskirchinger reviewed
Looks good to me.

2022-08-07 11:43 UTC, nlohmann approved these changes
Looks good to me.

2022-08-07 11:57 UTC, merged