Fix typos in .md files
nlohmann/json pull request #3748
Opened 2022-09-15 15:53 UTC by tocic

2022-09-15 16:06 UTC, falbrechtskirchinger requested changes

2022-09-15 16:06 UTC, falbrechtskirchinger commented on .github/PULL_REQUEST_TEMPLATE.md
> +- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for
That's still not correct.

```suggestion
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for this kind of bug). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
```

2022-09-15 16:06 UTC, falbrechtskirchinger commented on docs/mkdocs/docs/api/basic_json/update.md
> +    One common usecase for this function is the handling of user settings. Assume your application can be configured in
```suggestion
    One common use case for this function is the handling of user settings. Assume your application can be configured in
```

2022-09-15 16:06 UTC, falbrechtskirchinger commented on docs/mkdocs/docs/api/macros/nlohmann_json_serialize_enum.md
> +:   a pair of an enumerator and a JSON serialization; arbitrary pairs can be given as comma-separated list
```suggestion
:   a pair of an enumerator and a JSON serialization; arbitrary pairs can be given as a comma-separated list
```

2022-09-16 05:55 UTC, falbrechtskirchinger approved these changes
Looks good to me.

2022-09-17 08:34 UTC, merged

2022-09-17 08:34 UTC, nlohmann commented
Thanks!