Add serialization-only user defined type macros
nlohmann/json pull request #3816
Opened 2022-11-02 14:59 UTC by ZeronSix

This pull requests adds `NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_ONLY_SERIALIZE` and `NLOHMANN_DEFINE_TYPE_INTRUSIVE_ONLY_SERIALIZE` macros.

Suppose we have a non-default-constructible type `person` and another type that contains a field of type `person`. For example:
```cpp
#include <nlohmann/json.hpp>

#include <string>
#include <vector>

struct person {
    std::string name;
    int age;

    person(std::string name, int age)
        : name{std::move(name)}
        , age{age}
    {}
};

struct persons {
    std::vector<person> list;
};

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(person, name, age);
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(persons, list);
```
An attempt to use the `NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE` macro to generate serialization/deserialization code will lead to a compilation error:
```
test.cpp: In function ‘void from_json(const json&, persons&)’:
include/nlohmann/detail/macro_scope.hpp:385:81: error: no matching function for call to ‘nlohmann::json_abi_v3_11_2::basic_json<>::get_to(std::vector<person>&) const’
  385 | #define NLOHMANN_JSON_FROM(v1) nlohmann_json_j.at(#v1).get_to(nlohmann_json_t.v1);
```

`README.md` provides an example how to fix this by providing a specialization of `adl_serializer`. However, this requires writing quite a bit of code and might even be unnecessary in cases when we only need serialization without deserialization.

In this situations, we can use added macros to generate only `to_json` functions.
```cpp
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_ONLY_SERIALIZE(person, name, age);
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_ONLY_SERIALIZE(persons, list);
```

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [ ]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for this kind of bug). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

2023-09-23 13:37 UTC, nlohmann requested changes
Please add documentation. See https://github.com/nlohmann/json/blob/develop/docs/mkdocs/docs/api/macros/index.md for a starting point.

2023-09-24 09:14 UTC, nlohmann commented
(Also, please update from the develop branch as it has a working CI now.)

2023-10-02 09:01 UTC, ZeronSix commented
I also noticed that the source code highlighting is a bit off in these pages, see https://github.com/nlohmann/json/pull/4169.

2023-10-05 18:52 UTC, nlohmann approved these changes
Looks good to me.

2023-11-26 12:18 UTC, merged