Support Apple's Swift Package Manager
nlohmann/json pull request #4010
Opened 2023-04-14 08:59 UTC by aleksproger

**Reason**
- Main way to develop under Apple's platforms is using SPM

**Changes**
- Added Package.swift
- Added _SwiftPackageManagerFile.cpp to single_include/nlohmann in order SPM to see it as a C++ source file
- Added .build to .gitignore

**Context**
- SPM is a package manager for Swift and C-based languages. It is the main way to develop under Apple's platforms. It is also used to build Swift packages for Linux.
- Adding support for SPM will significantly simplify usage of this library for Apple platforms

[Describe your pull request here. Please read the text below the line, and make sure you follow the checklist.]

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [ ]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [ ]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [ ]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [ ]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for this kind of bug). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

2023-04-14 16:27 UTC, aleksproger commented
@nlohmann may you please re-trigger Ubuntu workflows? 
I see some of those failed, but suppose it should be flakinesses.

2023-04-14 17:59 UTC, nlohmann commented
No, there is an issue with the CI right now.

2023-05-26 07:21 UTC, aleksproger commented
@nlohmann may you trigger this one? As the CI now in a good state.

2023-06-11 08:02 UTC, nlohmann commented
Please update to the latest `develop` to have a fixed CI.

2023-06-19 04:32 UTC, aleksproger commented
@nlohmann rebased PR, have a look

2023-06-19 05:26 UTC, nlohmann commented on single_include/nlohmann/apple/_SwiftPackageManagerFile.cpp
Is this file really needed? I don’t like adding source files to this folder.

2023-06-19 05:53 UTC, aleksproger commented on single_include/nlohmann/apple/_SwiftPackageManagerFile.cpp
It wouldn't be needed if I'll bump the SwiftPM version to 5.9 which is shipped with Xcode 15.0 (the most recent one). If it's fine to you, then I can do that

2023-09-24 09:19 UTC, nlohmann requested changes

2023-09-24 09:19 UTC, nlohmann commented on single_include/nlohmann/apple/_SwiftPackageManagerFile.cpp
Now that Xcode 15 is released, can you update the MR?

2023-09-24 09:30 UTC, aleksproger commented on single_include/nlohmann/apple/_SwiftPackageManagerFile.cpp
Yep, sure, will do it soon

2023-09-24 09:31 UTC, nlohmann commented on single_include/nlohmann/apple/_SwiftPackageManagerFile.cpp
No worries - I made you wait for several months...

2023-10-04 18:19 UTC, aleksproger commented on single_include/nlohmann/apple/_SwiftPackageManagerFile.cpp
Done

2023-10-05 12:43 UTC, aleksproger commented
@nlohmann minGW checks have failed. May you retry or this is some persistent failure?

2023-10-05 12:54 UTC, nlohmann commented
It is fixed on the latest develop branch. Please update, it should work now.

2023-10-09 16:57 UTC, aleksproger commented
@nlohmann trigger CI, please

2023-10-12 11:51 UTC, aleksproger commented
@nlohmann trigger CI once again please
I had to update the PR, as I noticed deprecation warnings for and bumped the supported platforms for watchOS, tvOS
Otherwise it's good to merge and passed all the checks in previous iteration.

2023-10-20 17:00 UTC, richardtop commented
Looking forward to getting this merged!

2023-10-21 17:41 UTC, nlohmann approved these changes
Looks good to me.

2023-10-21 17:41 UTC, merged

2023-10-21 17:41 UTC, nlohmann commented
Thanks!