New macro for named JSON convertor generation
nlohmann/json pull request #4092
Opened 2023-08-01 22:35 UTC by radistmorse

This patch adds 4 new `NLOHMANN_DEFINE_TYPE_<***>_WITH_NAMES` macros. They behave the same way as the ones that are there, but require explicit JSON names. Useful for the situation when the fields in the class are following the naming convention that you do not want to expose to JSON, e.g.

```cpp
    class address {
      private:
        std::string m_street;
        int m_housenumber;
        int m_postcode;

      public:
        NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_NAMES(address, "street", m_street, "housenumber", m_housenumber, "postcode", m_postcode)
    };
```

or if the name in JSON cannot be used as the field name because it is reserved, e.g.

```cpp
    struct weird {
        std::string static_comp;
        std::string class_type;
        std::string public_field;
    };
    NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_NAMES(weird, "static", static_comp, "class", class_type, "public", public_field)
```

Also, this patch includes the unit tests for the new macros, and the update for the README to describe the new and existing macros better.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

2023-09-24 09:24 UTC, nlohmann requested changes
Please update to the latest develop branch and resolve conflicts.

2024-03-08 09:10 UTC, Hackerl commented
This feature is very good，when can it be merged?

2024-03-08 09:36 UTC, nlohmann commented
When the CI is not failing any more.

2024-12-20 19:50 UTC, radistmorse commented
I'll open a new PR since this one is quite stale

2024-12-20 19:50 UTC, closed without merging