Add support for BSON element 11: uint64
nlohmann/json pull request #4380
Opened 2024-05-24 12:59 UTC by slowriot

This MR adds support for decoding and encoding BSON element 11: 64bit unsigned int.

This resolves https://github.com/nlohmann/json/issues/3894.

## Changes
- Decode element `0x11` correctly as `uint64_t`.
- Update existing `write_bson_unsigned` to encode unsigned 64bit values correctly (using `0x11` instead of signed `0x12`).
- Update existing tests to expect support for `uint64_t`.

## Pull request checklist

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

2024-11-07 13:20 UTC, nlohmann requested changes
Thanks for the patience. The code looks good, but the documentation needs adjustment:

- https://github.com/nlohmann/json/blob/develop/docs/mkdocs/docs/home/exceptions.md: remove BSON from the description of `json.exception.out_of_range.407`
- https://github.com/nlohmann/json/blob/develop/docs/mkdocs/docs/features/binary_formats/bson.md: adjust mapping tables

2024-11-07 13:53 UTC, slowriot commented
> Thanks for the patience. The code looks good, but the documentation needs adjustment:
> 

Thanks for the review.  Documentation updated in latest.  Please let me know if I've missed anything else.

2024-11-07 14:34 UTC, nlohmann commented
Coverage went down. Can you please check if a test is missing?

2024-11-16 16:12 UTC, nlohmann requested changes

2024-11-16 16:12 UTC, nlohmann commented on include/nlohmann/detail/output/binary_writer.hpp
> +            JSON_THROW(out_of_range::create(407, concat("unsigned integer number ", std::to_string(j.m_data.m_value.number_unsigned), " cannot be represented by BSON as it does not fit into uint64"),
If I read the coverage information correctly, then this line is not covered in a test. Please check and add a test.

2024-11-16 16:13 UTC, nlohmann commented
(And also, please update to the latest develop branch so that the CI can be green)

2024-11-16 22:16 UTC, nlohmann commented
Btw: have you looked at #4356?

2025-01-10 18:41 UTC, nlohmann commented
We recently merged #4590. I think this PR can be closed.

2025-01-10 18:53 UTC, slowriot commented
> We recently merged #4590. I think this PR can be closed.

Thanks, just catching up with the changes since I last pushed to this PR - took a moment to resolve the conflicts as #4590 duplicated most of what I did, but it seems there may still have been a few changes in this PR that were missed in the other (unit test for example, and slightly different approach to choosing a format when encoding, documentation grammar, case ordering and a few other minor details).

Please review and let me know if any of it is still of use, and if it can be merged on top or if anything needs to be corrected or removed from this change.  Otherwise of course it can be closed.

2025-01-10 18:57 UTC, nlohmann commented
Sure, go ahead.

2025-01-10 19:12 UTC, slowriot commented
@nlohmann Having rebased, I think the [remaining changes](https://github.com/nlohmann/json/pull/4380/files) in this PR's diffs may still be useful to merge - please have a look.  Otherwise, please close.

2025-01-10 20:35 UTC, gregmarr commented on include/nlohmann/detail/output/binary_writer.hpp
> +            JSON_THROW(out_of_range::create(407, concat("unsigned integer number ", std::to_string(j.m_data.m_value.number_unsigned), " cannot be represented by BSON as it does not fit into uint64"),
I think this can only happen if `number_unsigned` has a larger size than 64 bits.  Does the library support that?  If not, then this can't be hit.

2025-01-11 14:51 UTC, nlohmann commented
@codenut Can you please have a look at the remaining diff?

2025-01-11 15:07 UTC, nlohmann requested changes
The remaining changes seem reasonable, but I would also like to get @codenut 's take on this.

- Please revert the whitespace changes in the documentation. I think there is only one grammar fix left then.
- There is an uncovered branch that can be removed as it would only be triggered with 128-bit integers.
- A call to `max` needs to be put in parentheses to fix the Windows builds.

2025-01-11 15:07 UTC, nlohmann commented on include/nlohmann/detail/output/binary_writer.hpp
> +               : sizeof(std::uint64_t);
This change seems reasonable.

2025-01-11 15:07 UTC, nlohmann commented on include/nlohmann/detail/output/binary_writer.hpp
> +            JSON_THROW(out_of_range::create(407, concat("unsigned integer number ", std::to_string(j.m_data.m_value.number_unsigned), " cannot be represented by BSON as it does not fit into uint64"),
So far, I failed to compile the library with 128-bit integers. For CBOR, we assume all unsigned integers to fit into 64 bits, so I think it's fair to do the same here. (Any code like the one above could not be tested anyway.)

2025-01-11 15:07 UTC, nlohmann commented on include/nlohmann/detail/output/binary_writer.hpp
> +            write_bson_entry_header(name, 0x11 /* uint64 */);
This change seems reasonable.

2025-01-11 15:07 UTC, nlohmann commented on tests/src/unit-bson.cpp
> +                        0x11u, /// entry: uint64
This is a consequence of the change in `write_bson_unsigned` above.

2025-01-11 15:07 UTC, nlohmann commented on include/nlohmann/detail/output/binary_writer.hpp
> +        else if (j.m_data.m_value.number_unsigned <= std::numeric_limits<std::uint64_t>::max())
The call to `max` needs to be put in parentheses to work with MSVC. This is the reason the Windows jobs are currently failing.

2025-01-11 16:28 UTC, slowriot commented
> The remaining changes seem reasonable, but I would also like to get @codenut 's take on this.
> 
>     * Please revert the whitespace changes in the documentation. I think there is only one grammar fix left then.
> 
>     * There is an uncovered branch that can be removed as it would only be triggered with 128-bit integers.
> 
>     * A call to `max` needs to be put in parentheses to fix the Windows builds.

Thanks for reviewing.  I've merged in the latest develop branch which already includes equivalent changes for a lot of the original PR, and tidied up the remaining diffs.  Please let me know if there's anything outstanding to address.

2025-01-11 16:37 UTC, nlohmann commented
Please check  https://github.com/nlohmann/json/pull/4380/checks?check_run_id=35473431508on how to fix the DCO warning.

2025-01-12 01:12 UTC, codenut commented on include/nlohmann/detail/output/binary_writer.hpp
> +            write_bson_entry_header(name, 0x11 /* uint64 */);
This change is logical, but I have some concerns about backward compatibility. It may break the following scenario:

```
void write()
{
    const uint64_t = 9223372036854775807L;
    json const j = {
            {"entry", l}
    };
    const std::vector<uint8_t> bson = json::to_bson(j);
    saveToTable1(bson);
    saveToTable2(bson);
}

write(); // was called before the code changes in this PR
```

```
void read()
{
    const std::vector<uint8_t> bson1 = loadFromTable1();
    json const j = json::from_bson(bson);
    const std::vector<uint8_t> bson1_roundtrip = json::to_bson(j);

    const std::vector<uint8_t> bson2 = loadFromTable2();

    if (equals(bson1_roundtrip, bson2)) { 
        ...
    }
}

read(); 
```

With the changes in this PR, the comparison between `bson1_roundtrip` and `bson2` will fail. It is hard to tell if clients rely on this behavior, but I would like to highlight this potential issue.

2025-01-12 10:33 UTC, nlohmann commented
(The coverage job is broken also in other branches. I am looking into this)

2025-01-15 17:10 UTC, nlohmann commented
The coverage job is now fixed in the `develop` branch. Please update.

2025-01-18 09:48 UTC, nlohmann requested changes

2025-01-18 09:48 UTC, nlohmann commented on include/nlohmann/detail/output/binary_writer.hpp
> +            write_bson_entry_header(name, 0x11 /* uint64 */);
For compatibility, we could serialize unsigned integers until int64_max with 0x12 and all numbers larger with 0x11.

2025-01-18 09:49 UTC, nlohmann commented
Please update to the latest `develop` branch and check https://github.com/nlohmann/json/pull/4380/checks?check_run_id=35473431508 on how to fix the DCO warning.

2025-04-12 12:15 UTC, nlohmann commented
#4590 was merged.

2025-04-12 12:15 UTC, closed without merging