Possible fix for #4485
nlohmann/json pull request #4487
Opened 2024-11-06 06:08 UTC by jordan-hoang

**Description**

This fixes an issue with getting a crash when passing in a null string to json::parse(). It instead throws an exception.
Also added in a testcase to check for this, though it's not in an appropriate file yet.

This is a bit of a rough draft.

* * *

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [ ]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [ ]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [ ]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

2024-11-08 20:38 UTC, nlohmann requested changes

2024-11-08 20:38 UTC, nlohmann commented on tests/src/unit-concepts.cpp
> +// This probably shouldn't go here..... should be in some other test file, since this has nothing to do with concepts.
Yes, this should go to tests/src/unit-deserialization.cpp.

2024-11-08 20:38 UTC, nlohmann commented on tests/src/unit-concepts.cpp
> +        CHECK_THROWS_AS(nlohmann::json::parse(string), std::exception);
Please use `CHECK_THROWS_WITH_AS` just as the other exception tests.

2024-11-08 20:38 UTC, nlohmann commented on include/nlohmann/detail/input/input_adapters.hpp
> +        JSON_THROW(std::invalid_argument("cannot parse a null string"));
Please throw `json::parse_error`. Please check `docs/mkdocs/docs/home/exceptions.md` for an overview.

2024-11-17 09:57 UTC, nlohmann requested changes
Please also consider the case that

```cpp
nlohmann::json::parse(nullptr);
```

is called. This is then interpreted as `FILE*`, so please adjust `inline file_input_adapter input_adapter(std::FILE* file)` to also throw and exception if `nullptr` is provided.

2024-11-17 09:58 UTC, nlohmann commented
(Also, please update to the latest develop branch to have a green CI)

2024-11-17 21:58 UTC, jordan-hoang commented
Gotcha, ahh so that's what it is, I noticed errors going away when I updated / merged from develop.
Thanks for letting me know.

2024-11-18 06:50 UTC, nlohmann requested changes
Please run "make amalgamate" using Astyle 3.1 (https://astyle.sourceforge.net) to fix the CI issues.

2024-11-18 06:50 UTC, nlohmann commented on include/nlohmann/detail/input/input_adapters.hpp
> +    if(file == nullptr)
Please add a test for this.

2024-11-18 07:19 UTC, nlohmann commented
Note "make pretty" is not sufficient as it only indents the files in `include` and `tests`. You must run "make amalgamate" to create the single header files in `single_includes`.

2024-11-18 10:00 UTC, jordan-hoang commented
Oh I see, I thought the single_include files weren't ever supposed to be changed.... Hmm seems like another check failed?

2024-11-18 10:44 UTC, nlohmann commented
> Oh I see, I thought the single_include files weren't ever supposed to be changed. But I realized that meant they weren't supposed to be manually edited, but rather generated with make amalgamate and then pushed.

You are right - the file should not be edited, because any changes would be overwritten once the amalgamation is triggered next time. To avoid this, we have this (rather picky) check in the CI that makes sure the files never differ.

> It's my first time trying out open source so sorry about that.

Please don't worry! Thanks for contributing!

2024-11-18 11:24 UTC, nlohmann commented
I will have a look at the remaining errors.

2024-11-18 11:25 UTC, nlohmann commented on tests/src/unit-deserialization.cpp
> +            CHECK_THROWS_WITH_AS(nlohmann::json::parse(string), "[json.exception.parse_error.101] parse error: attempting to parse an empty input; check that your input string or stream contains the
```suggestion
            json _;
            CHECK_THROWS_WITH_AS(_ = json::parse(string), "[json.exception.parse_error.101] parse error: attempting to parse an empty input; check that your input string or stream contains the expected JSON", json::parse_error&);
```

2024-11-18 11:26 UTC, nlohmann commented on tests/src/unit-deserialization.cpp
> +            CHECK_THROWS_WITH_AS(nlohmann::detail::input_adapter(nullptr), "[json.exception.parse_error.101] parse error: attempting to parse an empty input; check that your input string or stream co
```suggestion
            CHECK_THROWS_WITH_AS(_ = json::parse(nullptr), "[json.exception.parse_error.101] parse error: attempting to parse an empty input; check that your input string or stream contains the expected JSON", json::parse_error&);
```

2024-11-18 11:30 UTC, nlohmann commented on include/nlohmann/detail/input/input_adapters.hpp
> +        JSON_THROW(parse_error::create(101, 0, "attempting to parse an empty input; check that your input string or stream contains the expected JSON", nullptr));
Add

```cpp
#include <nlohmann/detail/exceptions.hpp>
#include <nlohmann/detail/macro_scope.hpp>
```

to use `parse_error` and `JSON_THROW`.

2024-11-18 11:30 UTC, nlohmann requested changes
I added some comments to fix some errors in the CI.

2024-11-18 11:31 UTC, nlohmann commented on tests/src/unit-deserialization.cpp
> +            CHECK_THROWS_WITH_AS(nlohmann::json::parse(string), "[json.exception.parse_error.101] parse error: attempting to parse an empty input; check that your input string or stream contains the
(Fixes the warning that the result of `parse` is unused.)

2024-11-18 11:31 UTC, nlohmann commented on tests/src/unit-deserialization.cpp
> +            CHECK_THROWS_WITH_AS(nlohmann::detail::input_adapter(nullptr), "[json.exception.parse_error.101] parse error: attempting to parse an empty input; check that your input string or stream co
(Fixes the warning that the result of `parse` is unused. Furthermore, the user will call `parse` and not create an input adapter.)

2024-11-19 07:24 UTC, nlohmann requested changes
One minor comment.

2024-11-19 07:24 UTC, nlohmann commented on include/nlohmann/detail/input/input_adapters.hpp
> +#include <nlohmann/detail/exceptions.hpp>
For stylistic reasons, please move this include down right above

```cpp
#include <nlohmann/detail/iterators/iterator_traits.hpp>
```

2024-11-19 07:52 UTC, jordan-hoang commented
Sorry about all these tiny commits, I make the changes on a windows push em and then do the make amalgamate on a linux vm I have. Should really get make setup for windows so I don't have to do that.

2024-11-19 07:58 UTC, nlohmann approved these changes
Looks good to me.

2024-11-19 12:54 UTC, merged

2024-11-19 12:54 UTC, nlohmann commented
Thanks a lot!!!