Allow ordered_json in NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE macro
nlohmann/json pull request #4528
Opened 2024-12-06 06:46 UTC by ArashPartow

Allow for `ordered_json `type to be used with the define macros provided in `macro_scope.hpp`.

Usage:

```
#include <cstdio>

#include <nlohmann/json.hpp>

struct mystruct
{
    int x = 1;
    double y = 2.0;
    std::string z = "three";
};

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE
(
    mystruct,
    z,
    y,
    x
);

int main()
{
    mystruct ms;

    const auto msjson = nlohmann::to_string(nlohmann::ordered_json{{ "mystruct", ms }});

    const std::string expected = R"({"mystruct":{"z":"three","y":2.0,"x":1}})";

    printf("%s\n",msjson  .c_str());
    printf("%s\n",expected.c_str());

    return 0;
}
```

2024-12-06 16:38 UTC, gregmarr commented
This version in enum handling is what they should really be:

```
    template<typename BasicJsonType>                                                            \
    inline void from_json(const BasicJsonType& j, ENUM_TYPE& e)                                 \
```

2024-12-06 16:41 UTC, gregmarr commented
See also #2843 and #2532

2024-12-10 20:18 UTC, nlohmann requested changes
I agree with https://github.com/nlohmann/json/pull/4528#issuecomment-2523699499 - a templated version would be a cleaner solution. Especially if more specializations are added such as #4517.

2024-12-10 22:36 UTC, ArashPartow commented
@nlohmann Happy for you to close this PR, as https://github.com/nlohmann/json/pull/4517 might be the more appropriate PR to make the necessary changes.

2025-01-18 22:00 UTC, nlohmann commented
Closed in favor of #4597.

2025-01-18 22:00 UTC, closed without merging