New macros for the named JSON convertor generation
nlohmann/json pull request #4563
Opened 2024-12-20 20:01 UTC by radistmorse

This patch adds several new `NLOHMANN_DEFINE_<***>_WITH_NAMES` macros. They behave the same way as the ones without `WITH_NAMES`, but require explicit JSON names. Useful for the situation when the fields in the class are following the naming convention that you do not want to expose to JSON, e.g.

```cpp
    class address {
      private:
        std::string m_street;
        int m_housenumber;
        int m_postcode;

      public:
        NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_NAMES(address, "street", m_street, "housenumber", m_housenumber, "postcode", m_postcode)
    };
```

or if the name in JSON cannot be used as the field name because it is reserved, e.g.

```cpp
    struct weird {
        std::string static_comp;
        std::string class_type;
        std::string public_field;
    };
    NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_NAMES(weird, "static", static_comp, "class", class_type, "public", public_field)
```

Also, this patch includes the unit tests for the new macros, and the update for the documentation.

It also fixes a small error in the docs where the `DEFINE_TYPE` macros were said to support up to 64 member variables, when in reality it is 63.

This is the update to the #4092 which didn't pass the amalgamation test because I had an old version of astyle. I updated the patch to include the new `DERIVED` variations as well as `ONLY_SERIALIZE`. Hopefully this one will be better.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

2025-01-06 15:15 UTC, radistmorse commented
I see several PRs that can potentially conflict with this one (#4528, #4560), and I'd rather not do extra work in maintaining this patch, if it's going to be pointless anyway. @nlohmann can you at least tell what are the chances of accepting this PR?

There is an unsuccessful check in the static code analysis, but first, it's a false positive, it says that the three fields are not used, when they most definitely are, and second, it's in example files, which shouldn't be statically analysed in the first place. Examples should be demonstrative and clear, not statically correct.

2025-01-06 15:19 UTC, nlohmann commented
I think having `_WITH_NAMES` macros are a good idea, but maybe it makes sense to focus on this only after #4528 and #4560 are merged.

2025-01-06 20:59 UTC, gregmarr commented on README.md
> +- The `WITH_NAMES` macros should be used if you want custom names for you JSON fields, the ones without `WITH_NAMES` will use the member names for JSON fields.
for your

2025-01-06 20:59 UTC, gregmarr commented on README.md
> +For all the macros, the first parameter is the name of the class/struct, and all remaining parameters name the members. The `DERIVED` variants require additional second argument for the parent class.
The `DERIVED` part should probably go before "all remaining"

2025-01-06 20:59 UTC, gregmarr commented on include/nlohmann/detail/macro_scope.hpp
> +#define NLOHMANN_JSON_FROM_WITH_DEFAULT_WITH_NAME(v1, v2) nlohmann_json_t.v2 = nlohmann_json_j.value(v1, nlohmann_json_default_obj.v2);
This will need to be updated with the new null handling.

2025-01-23 17:38 UTC, nlohmann commented on README.md
> +If you just want to serialize/deserialize some structs, the `to_json`/`from_json` functions can be a lot of boilerplate. There are [**several macros**](https://json.nlohmann.me/api/macros/#serializat
What is a "dedicated DTO"?

2025-01-23 17:38 UTC, nlohmann commented on docs/mkdocs/docs/features/arbitrary_types.md
> +There are several macros to make your life easier as long as you want to use a dedicated DTO for JSON serialization. The macros are following the naming pattern, and you can chose the macro based on
What is a "dedicated DTO"?

2025-01-23 17:38 UTC, nlohmann commented on docs/mkdocs/docs/api/macros/nlohmann_define_type_with_names.md
> +:   json name that will be used for the next member variable
"json" -> "JSON"?

What is a "json name"?

2025-01-23 17:38 UTC, nlohmann commented on docs/mkdocs/docs/api/macros/nlohmann_define_type_with_names.md
> +# The Named Conversion Macros
The API pages always have the name of the function/macros as title.

2025-01-23 17:38 UTC, nlohmann commented on docs/mkdocs/docs/features/arbitrary_types.md
> +- All the macros start with `NLOHMANN_DEFINE`.
I like this explanation, but I am not sure if we should delete the table.

2025-01-23 17:38 UTC, nlohmann commented on docs/mkdocs/docs/features/arbitrary_types.md
> +??? examples
Leave this to "example" - `example` is the type of the environment. If you want to give a title, add it in quotes after:

```markdown
??? example "Example with named variables"
```

2025-01-23 17:55 UTC, radistmorse commented on README.md
> +If you just want to serialize/deserialize some structs, the `to_json`/`from_json` functions can be a lot of boilerplate. There are [**several macros**](https://json.nlohmann.me/api/macros/#serializat
what's a "JSON object"? :) Same thing. But I will revert the terminology. When I tried to reword it "JSON" appeared too often, so I wanted to use something else.

2025-01-23 17:56 UTC, radistmorse commented on docs/mkdocs/docs/api/macros/nlohmann_define_type_with_names.md
> +:   json name that will be used for the next member variable
How else would you call "a name which will be used for the corresponding value inside the JSON"?

2025-01-23 17:58 UTC, radistmorse commented on docs/mkdocs/docs/features/arbitrary_types.md
> +- All the macros start with `NLOHMANN_DEFINE`.
The table will have to be twice as long. Are you sure?

2025-01-23 17:59 UTC, radistmorse commented on docs/mkdocs/docs/features/arbitrary_types.md
> +- All the macros start with `NLOHMANN_DEFINE`.
It also will have to have an additional column for  names, and it is already a bit cropped on the right.

2025-01-23 18:34 UTC, gregmarr commented on docs/mkdocs/docs/api/macros/nlohmann_define_type_with_names.md
> +:   json name that will be used for the next member variable
> How else would you call "a name which will be used for the corresponding value inside the JSON"?

The string that will be used as the name of the object for the next value.

2025-01-26 18:49 UTC, gregmarr commented
@nlohmann Do you think this is close enough to ready to have it in the next release?  It seems like a good complement to what's in there now for these macros.

2025-01-26 18:55 UTC, nlohmann commented
> @nlohmann Do you think this is close enough to ready to have it in the next release?  It seems like a good complement to what's in there now for these macros.

Sure - I'm in no rush for the release. And by starting with the release notes one gets an idea about the theme of the release, and yes, the named macros make sense to be added.

2025-01-26 21:51 UTC, nlohmann commented on docs/mkdocs/docs/features/arbitrary_types.md
> +- All the macros start with `NLOHMANN_DEFINE`.
Please leave it in.

2026-05-09 09:26 UTC, nlohmann commented
Can you please rebase to the latest develop branch?

2026-05-12 13:09 UTC, nlohmann requested changes

2026-05-12 13:09 UTC, nlohmann commented on README.md
> +        std:string email;
```suggestion
        std::string email;
```

2026-05-12 13:09 UTC, nlohmann commented on docs/mkdocs/docs/api/macros/index.md
> +  class
```suggestion
  class; uses custom names
```

2026-05-12 19:07 UTC, nlohmann requested changes
Please check the DTO requirements and the issue below.

2026-05-12 19:07 UTC, nlohmann commented on docs/mkdocs/docs/features/arbitrary_types.md
> +- All the macros start with `NLOHMANN_DEFINE`.
This issue is still open.

2026-05-13 10:37 UTC, radistmorse commented on docs/mkdocs/docs/features/arbitrary_types.md
> +- All the macros start with `NLOHMANN_DEFINE`.
I restored the table in the next commit. Do you want it somehow changed?

2026-05-13 11:12 UTC, radistmorse commented
The sign-off requirement is not that easy to fulfil retroactively. When I opened this PR there was no such requirement, and now after several merges from develop the simple `rebase` won't do it. It would be easier to just open a new PR. Again. Is it really that needed? I can confirm that I'm the sole author of these commits and that I have the right to sign them off under any license of my choosing. Also, I'm working in a scientific institution, not in a commercial company, contributing to open-source projects is literally in my job description. There is absolutely zero chance of any legal problems.

2026-05-13 11:46 UTC, nlohmann commented
I'm fine with ignoring DCO. I'll give a final review later this week.

2026-05-16 08:04 UTC, nlohmann approved these changes
Looks good to me.

2026-05-16 08:04 UTC, merged

2026-05-16 08:04 UTC, nlohmann commented
Thanks a lot!